"""sovereignty.py — Faction-to-country emergence.

Phase 6 Module 3: When a faction controls territory, population, and resources,
and has survived conflict, it can declare independence and become a new sovereign country.
The ultimate expression of emergent geopolitics — 5 countries can become 6, 7, or more.
"""

import json
import time
import random
from typing import Optional, Dict, Any, List, Tuple

COUNTRIES = ["solara", "valdris", "mirithane", "arkos", "verge"]
COUNTRY_NAMES = {
    "solara": "Solara",
    "valdris": "Valdris",
    "mirithane": "Mirithane",
    "arkos": "Arkos",
    "verge": "The Verge",
}

# ── Sovereignty thresholds ───────────────────────────────────────

SOVEREIGNTY_THRESHOLDS = {
    "territory_control": 0.6,     # Faction must control significant territory
    "member_count": 300,          # At 60K scale: 300 members to be viable
    "conflict_survival_ticks": 3, # Must survive 3+ ticks at armed_conflict+
    "recognition_count": 1,       # At least 1 external country must recognize
}

# Countries generated by secession
SEECESSION_COUNTERS: Dict[str, int] = {}

# Global secession cascade — boost faction formation globally after a successful secession
SECESSION_CASCADE_ACTIVE = False
SECESSION_CASCADE_TICKS_REMAINING = 0
SECESSION_CASCADE_BOOST = 0.5  # +50% faction formation probability


def check_sovereignty_thresholds(
    db,
    faction: Dict[str, Any],
    world_id: str,
    tick_number: int,
) -> Dict[str, Tuple[Any, Any, bool]]:
    """Check which sovereignty thresholds the faction meets.

    Returns: {threshold_name: (current_value, required_value, met)}
    """
    faction_id = faction["faction_id"]
    member_count = int(faction.get("member_count", 0))

    # Territory control: estimated from member count relative to total NPCs in region
    total_npcs = db.execute(
        "SELECT COUNT(*) FROM agents WHERE type = 'npc' AND state = 'active'"
    ).fetchone()[0] or 1
    territory_control = min(member_count / max(total_npcs * 0.3, 1), 1.0)

    # Conflict survival: count ticks at armed_conflict+ from sovereignty_events
    conflict_ticks_row = db.execute("""
        SELECT COUNT(DISTINCT tick_number) FROM sovereignty_events
        WHERE faction_id = ? AND event_type LIKE 'escalation:arm%'
    """, (faction_id,)).fetchone()
    conflict_survival = conflict_ticks_row[0] if conflict_ticks_row else 0

    # Recognition: count unique countries that have generated recognition events
    recognition_row = db.execute("""
        SELECT recognized_by FROM sovereignty_events
        WHERE faction_id = ? AND event_type = 'recognition' AND recognized_by IS NOT NULL
        ORDER BY id DESC LIMIT 1
    """, (faction_id,)).fetchone()
    recognition_count = 0
    recognized_by = []
    if recognition_row and recognition_row[0]:
        try:
            recognized_by = json.loads(recognition_row[0])
        except (json.JSONDecodeError, TypeError):
            try:
                recognized_by = recognition_row[0].split(",")
            except Exception:
                recognized_by = []
        recognition_count = len(recognized_by)

    return {
        "territory_control": (round(territory_control, 3), SOVEREIGNTY_THRESHOLDS["territory_control"], territory_control >= SOVEREIGNTY_THRESHOLDS["territory_control"]),
        "member_count": (member_count, SOVEREIGNTY_THRESHOLDS["member_count"], member_count >= SOVEREIGNTY_THRESHOLDS["member_count"]),
        "conflict_survival_ticks": (conflict_survival, SOVEREIGNTY_THRESHOLDS["conflict_survival_ticks"], conflict_survival >= SOVEREIGNTY_THRESHOLDS["conflict_survival_ticks"]),
        "recognition_count": (recognition_count, SOVEREIGNTY_THRESHOLDS["recognition_count"], recognition_count >= SOVEREIGNTY_THRESHOLDS["recognition_count"]),
    }


def check_declaration(
    db,
    faction: Dict[str, Any],
    world_id: str,
    tick_number: int,
    diplomatic_relations: Optional[Dict[str, Dict[str, float]]] = None,
) -> Optional[Dict[str, Any]]:
    """Check if a faction meets sovereignty thresholds and rolls for independence.

    Returns a declaration event dict, or None.
    """
    thresholds = check_sovereignty_thresholds(db, faction, world_id, tick_number)
    all_met = all(v[2] for v in thresholds.values())
    if not all_met:
        return None

    # Base declaration probability
    base_prob = 0.01
    influence = float(faction.get("influence", 0.3))
    territory = thresholds["territory_control"][0]
    recognition = thresholds["recognition_count"][0]

    prob = base_prob * (1.0 + influence) * (1.0 + territory) * (1.0 + recognition * 0.5)
    prob = min(prob, 0.5)

    if random.random() > prob:
        return None

    # DECLARE INDEPENDENCE
    faction_id = faction["faction_id"]
    faction_name = faction["name"]
    region = faction.get("region", world_id)

    # Generate new country name
    new_name = _generate_country_name(faction_name, world_id, region)

    db.execute("""
        INSERT INTO sovereignty_events (faction_id, world_id, event_type, new_country_name,
            territory_control, member_count, tick_number, created_at)
        VALUES (?, ?, 'declaration', ?, ?, ?, ?, ?)
    """, (faction_id, world_id, new_name, territory, int(faction.get("member_count", 0)), tick_number, time.time()))

    # Update faction status
    db.execute(
        "UPDATE factions SET status = 'declaring' WHERE faction_id = ?",
        (faction_id,)
    )
    db.commit()

    return {
        "event_type": "independence_declaration",
        "category": "sovereignty",
        "title": f"{new_name} declares independence from {COUNTRY_NAMES.get(world_id, world_id)}",
        "description": f"The faction '{faction_name}' has declared independence as the sovereign "
                       f"state of {new_name}, seceding from {COUNTRY_NAMES.get(world_id, world_id)}. "
                       f"Territory control: {territory:.1%}, members: {faction.get('member_count', 0)}, "
                       f"recognized by: {int(thresholds['recognition_count'][0])} countries.",
        "importance": 1.0,
        "actor_ids": [faction.get("leader_npc_id", "")],
        "tags": ["sovereignty", "independence", "declaration", world_id, region],
        "payload": {
            "faction_id": faction_id,
            "new_country_name": new_name,
            "parent_country": world_id,
            "thresholds": {k: v[0] for k, v in thresholds.items()},
        },
        "new_country_name": new_name,
    }


def process_recognition(
    db,
    faction: Dict[str, Any],
    world_id: str,
    new_country_name: str,
    tick_number: int,
    diplomatic_relations: Optional[Dict[str, Dict[str, float]]] = None,
) -> List[str]:
    """After declaration, other countries roll for recognition.

    Returns list of recognizing country IDs.
    """
    if diplomatic_relations is None:
        diplomatic_relations = _load_diplomatic_relations()

    recognizing = []
    for other in COUNTRIES:
        if other == world_id:
            continue

        pair = sorted([world_id, other])
        pair_key = f"{pair[0]}|{pair[1]}"
        rels = diplomatic_relations.get(pair_key, {})
        tension = rels.get("tension", 0.3)
        trust = rels.get("trust", 0.5)

        # Recognition probability
        base_prob = 0.2  # 20% base chance

        # Higher tension with parent country → more likely to recognize secessionists
        if tension > 0.5:
            base_prob += 0.3

        # Higher trust with parent → less likely to recognize (don't undermine allies)
        if trust > 0.6:
            base_prob -= 0.1

        # Verge always has high recognition chance (it was itself unrecognized)
        if other == "verge":
            base_prob += 0.2

        # Arkos protects autonomy movements
        if other == "arkos" and faction.get("primary_grievance") in ("personhood", "autonomy"):
            base_prob += 0.15

        base_prob = max(0.05, min(base_prob, 0.8))

        if random.random() < base_prob:
            recognizing.append(other)
            db.execute("""
                INSERT INTO sovereignty_events (faction_id, world_id, event_type,
                    new_country_name, recognized_by, tick_number, created_at)
                VALUES (?, ?, 'recognition', ?, ?, ?, ?)
            """, (faction["faction_id"], world_id, new_country_name, other, tick_number, time.time()))

    if recognizing:
        db.commit()

    return recognizing


def apply_secession(
    db,
    faction: Dict[str, Any],
    new_country_name: str,
    world_id: str,
    recognized_by: List[str],
    tick_number: int,
) -> Dict[str, Any]:
    """Finalize secession: split region, create new country entry, log the event.

    This is the irreversible step — the faction becomes a sovereign entity.
    """
    faction_id = faction["faction_id"]
    region = faction.get("region", "unknown")

    # Update faction status to sovereign
    db.execute(
        "UPDATE factions SET status = 'sovereign' WHERE faction_id = ?",
        (faction_id,)
    )

    # Log the secession
    db.execute("""
        INSERT INTO sovereignty_events (faction_id, world_id, event_type, new_country_name,
            recognized_by, territory_control, member_count, tick_number, created_at)
        VALUES (?, ?, 'secession', ?, ?, ?, ?, ?, ?)
    """, (
        faction_id, world_id, new_country_name,
        json.dumps(recognized_by),
        0.6,  # Estimated territory control
        int(faction.get("member_count", 0)),
        tick_number, time.time()
    ))

    # Reduce parent country population (faction members become new country citizens)
    members = db.execute(
        "SELECT npc_id FROM faction_members WHERE faction_id = ?", (faction_id,)
    ).fetchall()
    for m in members:
        db.execute(
            "UPDATE agents SET properties = json_set(COALESCE(properties, '{}'), '$.nationality', ?) WHERE id = ?",
            (new_country_name.lower(), m["npc_id"])
        )

    db.commit()

    # Trigger global secession cascade
    apply_secession_cascade(tick_number)

    return {
        "event_type": "secession_complete",
        "category": "sovereignty",
        "title": f"{new_country_name} is now a sovereign state",
        "description": f"The new country of {new_country_name} has been recognized by "
                       f"{', '.join(r.title() for r in recognized_by)} and is now "
                       f"independent from {COUNTRY_NAMES.get(world_id, world_id)}. "
                       f"Population: {faction.get('member_count', 0)}. "
                       f"This is the first territorial change in Aurelia's history.",
        "importance": 1.0,
        "actor_ids": [faction.get("leader_npc_id", "")],
        "tags": ["sovereignty", "secession", "new_country", new_country_name.lower(), world_id],
        "payload": {
            "new_country": new_country_name,
            "parent_country": world_id,
            "region": region,
            "recognized_by": recognized_by,
            "population": int(faction.get("member_count", 0)),
        },
    }


def apply_secession_cascade(tick_number: int):
    """Boost faction formation globally after a successful secession (Springtime of Nations)."""
    global SECESSION_CASCADE_ACTIVE, SECESSION_CASCADE_TICKS_REMAINING
    SECESSION_CASCADE_ACTIVE = True
    SECESSION_CASCADE_TICKS_REMAINING = 10


def process_sovereignty_tick(
    db,
    world_id: str,
    tick_number: int,
    diplomatic_relations: Optional[Dict[str, Dict[str, float]]] = None,
) -> List[Dict[str, Any]]:
    """Process sovereignty checks for all declaring factions in a world.

    Returns list of events.
    """
    global SECESSION_CASCADE_ACTIVE, SECESSION_CASCADE_TICKS_REMAINING

    events = []

    # Tick the cascade timer
    if SECESSION_CASCADE_ACTIVE:
        SECESSION_CASCADE_TICKS_REMAINING -= 1
        if SECESSION_CASCADE_TICKS_REMAINING <= 0:
            SECESSION_CASCADE_ACTIVE = False

    if diplomatic_relations is None:
        diplomatic_relations = _load_diplomatic_relations()

    # Check declaring factions
    declaring = db.execute(
        "SELECT * FROM factions WHERE world_id = ? AND status = 'declaring'",
        (world_id,)
    ).fetchall()

    for f in declaring:
        faction_dict = dict(f)
        faction_id = faction_dict["faction_id"]

        # Get the new country name from the declaration event
        decl_event = db.execute(
            "SELECT new_country_name FROM sovereignty_events WHERE faction_id = ? AND event_type = 'declaration' ORDER BY id DESC LIMIT 1",
            (faction_id,)
        ).fetchone()
        if not decl_event or not decl_event[0]:
            continue

        new_name = decl_event[0]

        # Process recognition
        recognizing = process_recognition(
            db, faction_dict, world_id, new_name, tick_number, diplomatic_relations
        )

        if len(recognizing) >= SOVEREIGNTY_THRESHOLDS["recognition_count"]:
            # Sufficient recognition → secession completes
            secession_event = apply_secession(
                db, faction_dict, new_name, world_id, recognizing, tick_number
            )
            events.append(secession_event)
        else:
            # Not enough recognition — declaration stalls
            events.append({
                "event_type": "declaration_stalled",
                "category": "sovereignty",
                "title": f"{new_name}'s independence stalled",
                "description": f"The declaration of independence by {new_name} has stalled. "
                               f"Only {len(recognizing)} countries have recognized it "
                               f"({', '.join(r.title() for r in recognizing) if recognizing else 'none'}). "
                               f"Needs {SOVEREIGNTY_THRESHOLDS['recognition_count']}.",
                "importance": 0.85,
                "actor_ids": [],
                "tags": ["sovereignty", "stalled", world_id],
                "payload": {
                    "new_country": new_name,
                    "recognized_by": recognizing,
                    "needed": SOVEREIGNTY_THRESHOLDS["recognition_count"],
                },
            })

    # Check factions that could potentially declare
    potential = db.execute(
        "SELECT * FROM factions WHERE world_id = ? AND status IN ('skirmish', 'armed_conflict')",
        (world_id,)
    ).fetchall()

    for f in potential:
        faction_dict = dict(f)
        decl_event = check_declaration(
            db, faction_dict, world_id, tick_number, diplomatic_relations
        )
        if decl_event:
            events.append(decl_event)

    return events


def get_sovereignty_candidates(db, world_id: str) -> List[Dict[str, Any]]:
    """Return factions that could potentially declare independence."""
    rows = db.execute(
        "SELECT * FROM factions WHERE world_id = ? AND status IN ('skirmish', 'armed_conflict', 'declaring')",
        (world_id,)
    ).fetchall()

    candidates = []
    for r in rows:
        faction_dict = dict(r)
        thresholds = check_sovereignty_thresholds(db, faction_dict, world_id, 0)
        met = sum(1 for v in thresholds.values() if v[2])
        total = len(thresholds)
        candidates.append({
            "faction_id": faction_dict["faction_id"],
            "name": faction_dict["name"],
            "status": faction_dict["status"],
            "members": faction_dict["member_count"],
            "influence": faction_dict["influence"],
            "thresholds_met": f"{met}/{total}",
            "thresholds": {k: v[0] for k, v in thresholds.items()},
        })
    return candidates


def is_secession_cascade_active() -> bool:
    return SECESSION_CASCADE_ACTIVE


def get_cascade_ticks_remaining() -> int:
    return SECESSION_CASCADE_TICKS_REMAINING


def get_cascade_boost() -> float:
    return SECESSION_CASCADE_BOOST if SECESSION_CASCADE_ACTIVE else 0.0


# ── Internal helpers ──────────────────────────────────────────────


def _generate_country_name(faction_name: str, parent_world: str, region: str) -> str:
    """Generate a country name from faction identity."""
    # Use region as primary source
    base = region.title()

    # Suffixes
    suffixes = [
        "Republic",
        "Free State",
        "Commonwealth",
        "Dominion",
        "Sovereign Territory",
        "Union",
        "Confederation",
    ]

    # If faction name contains a directional/descriptive word, use it
    words = faction_name.split()
    descriptive_words = [w for w in words if w.lower() not in ("the", "of", "in", "a", "an", "and")]
    if descriptive_words:
        # Use the most meaningful word
        for word in descriptive_words:
            if word[0].isupper() and len(word) > 3:
                base = word
                break

    return f"{base} {random.choice(suffixes)}"


def _load_diplomatic_relations() -> Dict[str, Dict[str, float]]:
    """Load diplomatic relations from coordinator DB."""
    try:
        import sqlite3
        cdb = sqlite3.connect("/Users/johann/aurelia/coordinator.db", timeout=2)
        cdb.row_factory = sqlite3.Row
        rows = cdb.execute(
            "SELECT relation_key, trust, tension, cooperation, trade FROM diplomatic_relations"
        ).fetchall()
        cdb.close()
        result = {}
        for r in rows:
            result[r["relation_key"]] = {
                "trust": r["trust"],
                "tension": r["tension"],
                "cooperation": r["cooperation"],
                "trade": r["trade"],
            }
        return result
    except Exception:
        return {}
